name: Fetch Docs

on:
  schedule:
    - cron: '5 * * * *'

  workflow_dispatch:

jobs:
  fetch-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Docs-Frontend Repository
        uses: actions/checkout@v3
        with:
          path: "."

      - name: Set Up Git Configuration
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch Docs from sources into /src
        run: |
          cd src

          if [ ! -d .git ]; then
            git init
            git remote add origin https://github.com/world-federation-of-advertisers/cross-media-measurement.git
            git sparse-checkout init --cone
          fi

          echo "README.md" > .git/info/sparse-checkout
          echo "docs" >> .git/info/sparse-checkout

          git pull origin main

      - name: Commit and Push Changes to Docs-Frontend
        run: |
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "docs: Pull latest documentation files"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
